l1=['H','S','G','M']
l2=[17,6,28,6,45,67,54,20]
len1=len(l1)
len2=len(l2)
print("Length of the 1st list is:",len1)
print("Length of the 2nd list is:",len2)
max1=max(l1)
max2=max(l2)
print("The element of maximum value from 1st list:",max1)
print("The element of maximum value from 2nd list:",max2)
min1=min(l1)
min2=min(l2)
print("The element of minimum value from 1st list:",min1)
print("The element of minimum value from 2nd list:",min2)
tup=("Hello","Students","Good","Morning")
l3=list(tup)
print("The new list:",l3)
l1.append(25)
print(l1)
print(l2.count(6))
print(l2.index(67))
l1.insert(2,'K')
print(l1)
print(l2.pop(4))
l2.remove(67)
print(l2)
l1.reverse()
print(l1)
l1.extend(l2)
print(l1)
l1.clear()
print(l1)
l5=l2.copy()
print(l5)
l5.sort()
print(l5)
